In [54]:
print("Hello World ~Matt Goeckel")

Hello World ~Matt Goeckel


In [55]:
##7.2 Creating arrays from Existing Data 
import numpy as np
numbers = np.array([2, 3, 5, 7, 11])
type(numbers)

numpy.ndarray

In [56]:
numbers

array([ 2,  3,  5,  7, 11])

In [57]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [60]:
##7.3 array Attributes
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
print(integers.dtype)
print(integers.ndim)
print(integers.shape)
print(integers.size)
print(integers.itemsize)

int32
2
(2, 3)
6
4


In [62]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [63]:
for i in integers.flat:
    print(i)

1
2
3
4
5
6


In [64]:
##7.4 Filling arrays with Specific Values
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [66]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [67]:
##7.5 Creating arrays from Ranges
np.arange(5)

array([0, 1, 2, 3, 4])

In [68]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [69]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [70]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [71]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [72]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [73]:
##7.6 List vs. array Performance: Introducing %timeit
import random
%timeit rolls_list = \
    [random.randrange(1, 7) for i in range(0, 6_000_000)]

3.98 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

56.8 ms ± 733 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

58.5 ms ± 1.17 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [76]:
## %load to read code into IPython from a local file or URL.
## %save to save snippets to a file.
## %run to execute a .py file from IPython.
## %precision to change the default floating-point precision for IPython outputs.
## %cd to change directories without having to exit IPython first.
## %edit to launch an external editor—handy if you need to modify more complex snippets.
## %history to view a list of a

In [77]:
##7.7 array Operators
numbers = np.arange(1, 6)
print(numbers)
print(numbers*2)
print(numbers ** 3)
print(numbers)
numbers += 10
print(numbers)

[1 2 3 4 5]
[ 2  4  6  8 10]
[  1   8  27  64 125]
[1 2 3 4 5]
[11 12 13 14 15]


In [78]:
numbers2 = np.linspace(1.1, 5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [79]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [80]:
numbers >= 13

array([False, False,  True,  True,  True])

In [81]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [82]:
##7.8 NumPy Calculation Methods
grades = np.array([[87, 96, 70], [100, 87, 90],[94, 77, 90], [100, 81, 82]])
print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())
print(grades.var())

1054
70
100
87.83333333333333
8.792357792739987
77.30555555555556


In [83]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [84]:
##7.9 Universal Functions
numbers = np.array([1, 4, 9, 16, 25, 36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [85]:
numbers2 = np.arange(1, 7) * 10
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [86]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [87]:
numbers3 = numbers2.reshape(2, 3)
numbers4 = np.array([2, 4, 6])
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [88]:
##7.10 Indexing and Slicing
grades[0, 1] # row 0, column 1

96

In [89]:
print(grades[1])
print("end of array")
print(grades[0:2])
print("end of array")
print(grades[[1,3]])
print("end of array")
print(grades[:,0])
print("end of array")
print(grades[:,1:3])
print("end of array")
print(grades[:, [0, 2]])

[100  87  90]
end of array
[[ 87  96  70]
 [100  87  90]]
end of array
[[100  87  90]
 [100  81  82]]
end of array
[ 87 100  94 100]
end of array
[[96 70]
 [87 90]
 [77 90]
 [81 82]]
end of array
[[ 87  70]
 [100  90]
 [ 94  90]
 [100  82]]


In [90]:
##7.11 Views: Shallow Copies
numbers = np.arange(1, 6)
print(numbers)
numbers2 = numbers.view()
print(numbers2)

[1 2 3 4 5]
[1 2 3 4 5]


In [91]:
print(id(numbers))
print(id(numbers2))

2762587168976
2762584657424


In [92]:
numbers[1] *= 10
print(numbers)
print(numbers2)

[ 1 20  3  4  5]
[ 1 20  3  4  5]


In [93]:
numbers2[1] /= 10
print(numbers)
print(numbers2)

[1 2 3 4 5]
[1 2 3 4 5]


In [94]:
numbers2 = numbers[0:3]
print(numbers)
print(numbers2)

[1 2 3 4 5]
[1 2 3]


In [95]:
##7.12 Deep Copies
numbers = np.arange(1, 6)
print(numbers)
numbers2 = numbers.copy()
print(numbers2)

[1 2 3 4 5]
[1 2 3 4 5]


In [96]:
numbers[1] *= 10
print(numbers)
print(numbers2)

[ 1 20  3  4  5]
[1 2 3 4 5]


In [97]:
##7.13 Reshaping and Transposing
grades = np.array([[87, 96, 70], [100, 87, 90]])
print(grades)
grades.reshape(1, 6) #returns a view

[[ 87  96  70]
 [100  87  90]]


array([[ 87,  96,  70, 100,  87,  90]])

In [98]:
grades.resize(1, 6) #resize actually modifies the array
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [99]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
flattened = grades.flatten()
flattened

array([ 87,  96,  70, 100,  87,  90])

In [100]:
flattened[0] = 100
print(flattened)
print(grades)       #DOES NOT share data

[100  96  70 100  87  90]
[[ 87  96  70]
 [100  87  90]]


In [101]:
raveled = grades.ravel()
raveled

array([ 87,  96,  70, 100,  87,  90])

In [102]:
raveled[0] = 100
print(raveled)
print(grades)       #DOES share data

[100  96  70 100  87  90]
[[100  96  70]
 [100  87  90]]


In [103]:
grades.T        #View with rows & columns flipped

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [104]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [105]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [107]:
##7.14 Dataframes
import pandas as pd
kitchen = pd.Series(['Sink', 'Dish', 'Fork'])
kitchen.str.contains('i')

0     True
1     True
2    False
dtype: bool

In [ ]:
kitchen.str.upper()

0    SINK
1    DISH
2    FORK
dtype: object

In [ ]:
temps = np.random.randint(60, 101, 6)
temperatures = pd.Series(temps)
print(temperatures)
print("LOW: " + str(temperatures.min()))
print("HIGH: " + str(temperatures.max()))
print("Average: " + str(temperatures.mean()))
print(temperatures.describe())

0    93
1    71
2    94
3    97
4    78
5    63
dtype: int32
LOW: 63
HIGH: 97
Average: 82.66666666666667
count     6.000000
mean     82.666667
std      14.038044
min      63.000000
25%      72.750000
50%      85.500000
75%      93.750000
max      97.000000
dtype: float64
